### PR TITLE
Documentation updated

### PR DESCRIPTION
**Pull request by mendelevium28**
__2__

#2 

Changes in Documentation

### CODE REVIEW

**Review by Jigar3 — APPROVED** [review]

**Comment by mendelevium28** [comment]
Sir, I didn't get points for this

**Comment by Jigar3** [comment]
@thesmallstar

**Comment by thesmallstar** [comment]
Wrong format of issue number, put it on slack.
You removed __

**Comment by mendelevium28** [comment]
I corrected the format sir, do i need to put it on slack?

**Pull request merged**
