### PR TITLE
Tests for functions in helper.go

### PR DESCRIPTION
**Pull request by untrulynoxiusmj**
7

#7 

Tests for functions in helper.go

### CODE REVIEW

**Comment by untrulynoxiusmj** [comment]
@Jigar3 sir, please review

**Review by Jigar3 — APPROVED** [review]
@untrulynoxiusmj Good Job

**Comment by untrulynoxiusmj** [comment]
@Jigar3 sir, i didn't get points for this pull request.

**Comment by Jigar3** [comment]
@thesmallstar

**Pull request merged**
